### PR TITLE
Add automatic differentiation to Numericeal section

### PR DESCRIPTION
**Pull request by aaronlevin**

### CODE REVIEW

**Comment by aaronlevin** [comment]
Resolves: https://github.com/Gabriel439/post-rfc/issues/5

**Comment by Gabriella439** [comment]
Sorry for the merge conflict.  This is because of another pull request that added hyperlinks to all package names.  I will resolve this conflict myself later tonight if you don't have time

**Comment by aaronlevin** [comment]
@Gabriel439 I resolved the merge conflict.

**Comment by Gabriella439** [comment]
Thanks! :)

**Pull request merged**
