### PR TITLE
[Compilers] Add `unbound` to the libraries section

### PR DESCRIPTION
**Pull request by co-dan**

### CODE REVIEW

**Comment by Gabriella439** [comment]
Sorry for the merge conflict. This is because of another pull request that added hyperlinks to all package names. I will resolve this conflict myself later tonight if you don't have time

**Comment by co-dan** [comment]
Sure, no hassle. Thank you for this effort. It is refreshing to see this constructive criticism. 

Btw, there is also a paper about the `unbound` package: http://ozark.hendrix.edu/~yorgey/pub/unbound.pdf if that is of interest.

**Comment by Gabriella439** [comment]
Yeah, the paper is worth adding to the Educational Resources section

**Comment by Gabriella439** [comment]
I merged in your change and added in the paper  as well

**Pull request merged**
